### ISSUE TITLE
在小米9上获取输入法高度失效。

### ISSUE THREAD

**Issue by universe-st** [demongel/SoftKeyboardHeight#1]

**Comment by universe-st** [comment]
ADJUST_NOTHING模式下使用PopupWindow获取到的高度是不正确的。

**Comment by UserName-Haha** [comment]
这个是刘海屏导致的，getWindowVisibleDisplayFrame方法获取的尺寸不准确，在handleOnGlobalLayout方法中判断下刘海屏，如果是刘海屏则将刘海屏高度算进去
